/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovc2VtZXN0ZXIgNC9QV0wvQmVsYWphciBBbmd1bGFyL2RlcGxveS1kZW1vL2RlcGxveS1kZW1vL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9zZW1lc3RlciA0L1BXTC9CZWxhamFyIEFuZ3VsYXIvZGVwbG95LWRlbW8vZGVwbG95LWRlbW8vc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
